name: Docker Image CI for GHCR

on:
  push 

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push the image 
        run: |
          docker login --username nfrank22-gh --password ${{secrets.GH_LOGIN_TOKEN}} ghcr.io
          docker build . --tag ghcr.io/nfrank22-gh/kf-da:latest 
          docker push ghcr.io/nfrank22-gh/kf-da:latest


